# Generated by Django 6.1.1 on 2026-09-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0017_alter_businessorganization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genmars_account_id', models.PositiveIntegerField(db_index=True, help_text='`account.id` from the sign-on token. The join key.', unique=True)),
                ('email', models.EmailField(help_text='As of the last sign-in. gen-portal is the source of truth.', max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Barred from this platform. Says nothing about their Genmars account, which this application does not get to disable.')),
            ],
            options={
                'verbose_name': 'Platform account',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='StaffCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=128)),
                ('must_change_password', models.BooleanField(default=True, help_text="A manager sets the first password, so they know it. Until it is changed, the cashier's actions are not solely attributable to them.")),
                ('is_active', models.BooleanField(default=True, help_text='Turned off when somebody leaves. The personnel record stays.')),
                ('failed_sign_ins', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credentials', to='organisations.businessorganization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='organisations.organizationstaff')),
            ],
            options={
                'ordering': ['organization__name', 'username'],
            },
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_prefix', models.CharField(db_index=True, max_length=12)),
                ('token_hash', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='identity.staffcredential')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Organisation admin'), ('accountant', 'Accountant')], default='admin', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='identity.platformaccount')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='identity.platformaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='organisations.businessorganization')),
            ],
            options={
                'ordering': ['organization__name', 'role'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffcredential',
            constraint=models.UniqueConstraint(fields=('organization', 'username'), name='one_username_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('account', 'organization'), name='one_membership_per_tenant'),
        ),
    ]
