# Generated by Django 6.1.1 on 2026-09-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_tenantinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hashed', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='identity.staffcredential')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['credential', '-created_at'], name='identity_st_credent_ceaaac_idx')],
            },
        ),
    ]
