# Generated by Django 6.1.1 on 2026-10-07 20:25

"""
Tell a first-day setup code apart from a forgotten-password one.

`default='reset'` is the load-bearing part. Every row that predates this
field was a forgotten-password code, and that is what it will now say. The
alternative — backfilling SETUP for rows whose credential currently has no
usable password — would be a guess, and it would be wrong in the one case it
matters: a login created with a password that nobody has got round to using
reads identically to one created without.

Nothing is backfilled and nothing needs to be: `purpose` is read when a code
is SPENT, and every code that predates this migration has long since expired
— the longest window before it was fifteen minutes.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_admintotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpasswordreset',
            name='purpose',
            field=models.CharField(choices=[('setup', 'First-time setup'), ('reset', 'Forgotten password')], default='reset', max_length=8),
        ),
    ]
