# Generated by Django 6.1.1 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogcategoryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
