# Generated by Django 6.1.1 on 2026-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogcategoryproduct_name_and_more'),
        ('organisations', '0017_alter_businessorganization_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategoryproduct',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.catalogcategories'),
        ),
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catalogcategoryproduct',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='catalogcategoryproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_product_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategoryproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='unique_product_sku_per_organization'),
        ),
    ]
