# Generated by Django 6.1.1 on 2026-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalogcategoryproduct_options_and_more'),
        ('organisations', '0018_alter_businessorganization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategories',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='catalogcategories',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_name_per_organization'),
        ),
    ]
