# Generated by Django 6.1.1 on 2026-09-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalogcategories_name_and_more'),
        ('organisations', '0024_businessorganization_genmars_organisation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategoryproduct',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "VAT 16%" or "Zero rated"', max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, help_text='A percentage. 16.00 means 16%, not 1600%.', max_digits=5)),
                ('is_inclusive', models.BooleanField(default=True, help_text='True when the shelf price already contains the tax.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='organisations.businessorganization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='catalogcategoryproduct',
            name='tax_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.taxrule'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategoryproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('organization', 'barcode'), name='unique_product_barcode_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_tax_rule_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='one_default_tax_rule_per_organization'),
        ),
    ]
