# Generated by Django 6.1.1 on 2026-10-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0022_registershift_note'),
        ('catalog', '0006_catalogcategoryproduct_barcode_taxrule_and_more'),
        ('organisations', '0025_businessorganization_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('precedence', models.PositiveSmallIntegerField(help_text='Higher wins. Unique within the business, so two lists can never both claim the same product at the same moment.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='organisations.businessorganization')),
            ],
            options={
                'ordering': ['-precedence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='branches.branches')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='catalog.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_entries', to='catalog.catalogcategoryproduct')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_price_list_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'precedence'), name='unique_price_list_precedence_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='price_list_window_is_not_backwards'),
        ),
        migrations.AddConstraint(
            model_name='pricelistbranch',
            constraint=models.UniqueConstraint(fields=('price_list', 'branch'), name='unique_branch_per_price_list'),
        ),
        migrations.AddConstraint(
            model_name='pricelistentry',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='unique_product_per_price_list'),
        ),
        migrations.AddConstraint(
            model_name='pricelistentry',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_list_entry_is_not_negative'),
        ),
    ]
