# Generated by Django 6.1.1 on 2026-10-10 20:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_pricelist_pricelistbranch_pricelistentry_and_more'),
        ('organisations', '0025_businessorganization_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategoryproduct',
            name='pack_name',
            field=models.CharField(blank=True, help_text='What one pack is called: carton, crate, sack, dozen.', max_length=40),
        ),
        migrations.AddField(
            model_name='catalogcategoryproduct',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many sellable units come in one bought pack. 24 for a carton of 24 bottles. Leave at 1 for anything bought the way it is sold.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='catalogcategoryproduct',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_pack__gt', 0)), name='a_pack_holds_at_least_something'),
        ),
    ]
