# Generated by Django 6.1.1 on 2026-10-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0022_registershift_note'),
        ('identity', '0005_staffpasswordreset_purpose'),
        ('organisations', '0025_businessorganization_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment.confirmed', 'Payment confirmed'), ('payment.failed', 'Payment failed'), ('stock.low', 'Stock is low'), ('stock.out', 'Out of stock'), ('order.awaiting', 'Purchase order awaiting approval'), ('count.awaiting', 'Stock take awaiting sign-off'), ('shift.closed', 'Till closed'), ('shift.short', 'Till closed short')], max_length=24)),
                ('urgency', models.CharField(choices=[('inform', 'Worth knowing'), ('attend', 'Needs somebody'), ('urgent', 'Needs somebody now')], default='inform', max_length=8)),
                ('permission', models.CharField(help_text='An identity.access permission name. Who may see this.', max_length=32)),
                ('subject', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=300)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('subject_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_caused', to='identity.platformaccount')),
                ('actor_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_caused', to='organisations.organizationstaff')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='branches.branches')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organisations.businessorganization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='identity.platformaccount')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='organisations.organizationstaff')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', '-created_at'], name='notificatio_organiz_f822ba_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subject_key', 'resolved_at'], name='notificatio_subject_7596be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['account', 'notification'], name='notificatio_account_5f745f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['staff', 'notification'], name='notificatio_staff_i_d09e16_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('staff__isnull', True)), models.Q(('account__isnull', True), ('staff__isnull', False)), _connector='OR'), name='read_belongs_to_exactly_one_principal'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('notification', 'account'), name='one_read_per_notification_per_account'),
        ),
        migrations.AddConstraint(
            model_name='notificationread',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', False)), fields=('notification', 'staff'), name='one_read_per_notification_per_staff'),
        ),
    ]
