# Generated by Django 6.1.1 on 2026-10-01 19:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_staffpasswordreset'),
        ('organisations', '0025_businessorganization_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used in code and in URLs. Never reused.', max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('branch_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('staff_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('register_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_offered', models.BooleanField(default=True, help_text='Whether new subscribers may choose it. A withdrawn plan keeps working for whoever is already on it — moving somebody off the terms they agreed to is a commercial decision, not a cleanup.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=14, help_text='Days after the period ends before anything narrows. Per subscription rather than global, so a customer who is reliably late can be given room without changing it for everybody.')),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organisations.businessorganization')),
                ('plan', models.ForeignKey(blank=True, help_text='Null while on trial, or on a bespoke arrangement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trial_started', 'Trial started'), ('plan_chosen', 'Plan chosen'), ('extended', 'Period extended'), ('grace_changed', 'Grace changed'), ('cancelled', 'Cancelled'), ('reinstated', 'Reinstated')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_events', to='identity.platformaccount')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
