# Generated by Django 6.1.1 on 2026-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0019_remove_staffassignment_unique_active_staff_assignment_and_more'),
        ('catalog', '0004_alter_catalogcategoryproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='branches.branches')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_inventory', to='catalog.catalogcategoryproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='unique_product_per_branch')],
            },
        ),
    ]
