# Generated by Django 6.1.1 on 2026-09-05 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('staff_size', models.CharField(choices=[('SM', '5'), ('MD', '15'), ('LG', '25')], default='MD')),
                ('org_number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Business Org',
                'verbose_name_plural': 'Business Organizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
