# Generated by Django 6.1.1 on 2026-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorganization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
