# Generated by Django 6.1.1 on 2026-09-05 23:25

import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_businessorganization_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorganization',
            name='org_number',
            field=models.CharField(default=organisations.models.OrgNumberGenerator, max_length=20),
        ),
    ]
