# Generated by Django 6.1.1 on 2026-09-05 23:36

import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_businessorganization_org_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorganization',
            name='org_number',
            field=models.CharField(default=organisations.models.OrgNumberGenerator, max_length=18, unique=True),
        ),
    ]
