# Generated by Django 6.1.1 on 2026-09-07 08:54

import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_businessorganization_org_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('kra_pin', models.CharField(blank=True, max_length=11, null=True)),
                ('id_number', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('OA', 'OrganizationAdmin'), ('FN', 'Finance'), ('OM', 'OperationsManager'), ('BM', 'BranchManager'), ('IM', 'InventoryManager'), ('AU', 'Auditor')], default='BM')),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('staff_number', models.CharField(default=organisations.models.staffNumberGenerator, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Staff Organization',
                'verbose_name_plural': 'Staff Organization',
                'ordering': ['-start_date'],
            },
        ),
    ]
