# Generated by Django 6.1.1 on 2026-09-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organizationstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationstaff',
            old_name='name',
            new_name='full_name',
        ),
    ]
