# Generated by Django 6.1.1 on 2026-09-07 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_rename_name_organizationstaff_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstaff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
