# Generated by Django 6.1.1 on 2026-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_organizationstaff_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
