# Generated by Django 6.1.1 on 2026-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_alter_organizationstaff_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
