# Generated by Django 6.1.1 on 2026-09-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_create_default_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationstaff',
            name='role',
        ),
    ]
