# Generated by Django 6.1.1 on 2026-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_remove_organizationstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='kra_pin',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
