# Generated by Django 6.1.1 on 2026-09-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_alter_organizationstaff_kra_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstaff',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationStaff', to='organisations.businessorganization'),
        ),
    ]
