# Generated by Django 6.1.1 on 2026-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_organizationstaff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='organization',
            field=models.CharField(max_length=155),
        ),
    ]
