# Generated by Django 6.1.1 on 2026-09-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0015_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.businessorganization'),
        ),
    ]
