# Generated by Django 6.1.1 on 2026-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorganization',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
