# Generated by Django 6.1.1 on 2026-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_alter_businessorganization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessorganization',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organizationstaff',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_staff_email_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationstaff',
            constraint=models.UniqueConstraint(fields=('organization', 'phone_number'), name='unique_staff_phone_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationstaff',
            constraint=models.UniqueConstraint(fields=('organization', 'id_number'), name='unique_staff_id_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationstaff',
            constraint=models.UniqueConstraint(fields=('organization', 'kra_pin'), name='unique_staff_kra_pin_per_organization'),
        ),
    ]
