# Generated by Django 6.1.1 on 2026-09-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0019_organizationstaff_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstaff',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='staff',
                to='organisations.businessorganization',
            ),
        ),
    ]