# Generated by Django 6.1.1 on 2026-09-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0021_remove_organizationstaff_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstaff',
            options={'ordering': ['-start_date'], 'verbose_name': 'Staff Organization', 'verbose_name_plural': 'Staff Organizations'},
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationstaff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
