# Generated by Django 6.1.1 on 2026-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0023_alter_businessorganization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessorganization',
            name='genmars_organisation_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The Genmars client this tenant belongs to, where there is one.', null=True),
        ),
    ]
