# Generated by Django 6.1.1 on 2026-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0024_businessorganization_genmars_organisation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessorganization',
            name='sector',
            field=models.CharField(choices=[('retail', 'Shop or retail counter'), ('hospitality', 'Restaurant, bar or café')], default='retail', help_text='Decides how the till looks. Changes nothing about the data.', max_length=16),
        ),
    ]
