# Generated by Django 6.1.1 on 2026-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('counter', 'At the counter'), ('dine_in', 'Dine in'), ('take_away', 'Take away'), ('delivery', 'Delivery')], default='counter', max_length=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='table_name',
            field=models.CharField(blank=True, default='', help_text='Whatever the restaurant calls it — Table 4, Terrace 2, Bar. Free text rather than a foreign key: a floor plan is a bigger thing than this one field.', max_length=40),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='note',
            field=models.CharField(blank=True, default='', help_text='What the customer asked for on this line — no onions, medium, extra hot. Snapshotted like the price, so a receipt reprinted next year still says what was ordered.', max_length=200),
        ),
    ]
