# Generated by Django 6.1.1 on 2026-10-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_pricelist_pricelistbranch_pricelistentry_and_more'),
        ('sales', '0002_sale_order_type_sale_table_name_saleitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.pricelist'),
        ),
    ]
