# Generated by Django 6.1.1 on 2026-10-10 01:42

from django.db import migrations, models

# ── NO DEFAULT, AND THAT IS THE POINT ───────────────────────────────────────
#
# Every refund already written gets `""`, meaning "nobody recorded how this
# went back", and `branches.services.drawer` counts only `cash`. So no shift
# that has already been counted and closed has its expected cash restated by
# this migration — which backfilling `cash` here would have done, silently,
# to every one of them.
#
# Services refuse to write a blank one, so the set of blanks is fixed at
# whatever existed today and can only shrink.


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank transfer'), ('credit', 'On account')], help_text='How the money was given back. Blank only on refunds recorded before this was tracked.', max_length=10),
        ),
    ]
