# Generated by Django 6.1.1 on 2026-10-10 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_refund_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='usual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
