# Generated by Django 6.1.1 on 2026-09-07 21:34

import branches.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=38, verbose_name='Kilimani Branch')),
                ('branch_location', models.CharField(max_length=155, verbose_name='Kilimani, Opposite Naivas Supper Market')),
                ('branch_allocation', models.CharField(max_length=255)),
                ('branch_manager', models.CharField(max_length=15, unique=True)),
                ('branch_number', models.CharField(default=branches.models.branch_number_generator, max_length=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
