# Generated by Django 6.1.1 on 2026-09-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_location',
            field=models.CharField(max_length=155),
        ),
    ]
