# Generated by Django 6.1.1 on 2026-09-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branches_branch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_name',
            field=models.CharField(max_length=38),
        ),
    ]
