# Generated by Django 6.1.1 on 2026-09-08 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branches_organization'),
        ('organisations', '0012_remove_organizationstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organisations.businessorganization'),
        ),
    ]
