# Generated by Django 6.1.1 on 2026-09-08 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branches_organization'),
        ('organisations', '0012_remove_organizationstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organisations.businessorganization'),
        ),
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='branches.branches'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
