# Generated by Django 6.1.1 on 2026-09-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_number',
            field=models.CharField(max_length=100),
        ),
    ]
