# Generated by Django 6.1.1 on 2026-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_alter_branches_organization_alter_register_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
