# Generated by Django 6.1.1 on 2026-09-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_alter_register_name_alter_register_register_number'),
        ('organisations', '0016_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='OPEN', max_length=20)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_shifts', to='organisations.organizationstaff')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='branches.register')),
            ],
        ),
    ]
