# Generated by Django 6.1.1 on 2026-09-09 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_registershift'),
        ('organisations', '0016_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershift',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='staffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('staff_assignment', models.CharField(choices=[('AM', 'Assistant manager'), ('CA', 'Cashier'), ('SA', 'Sales Associate'), ('IC', 'Inventory Clerk'), ('PO', 'Purchasing Officer'), ('FC', 'Finance Clerk'), ('BA', 'Branch Auditor')], default='CA')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branches')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organisations.organizationstaff')),
            ],
        ),
    ]
