# Generated by Django 6.1.1 on 2026-09-09 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_alter_staffassignment_branch_and_more'),
        ('organisations', '0016_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='branches.branches'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organisations.organizationstaff'),
        ),
    ]
