# Generated by Django 6.1.1 on 2026-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0018_alter_staffassignment_branch_and_more'),
        ('organisations', '0016_alter_organizationstaff_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffassignment',
            name='unique_active_staff_assignment',
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff_member', 'branch', 'staff_assignment'), name='unique_active_staff_role_per_branch'),
        ),
    ]
