# Generated by Django 6.1.1 on 2026-09-21 11:37

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0019_remove_staffassignment_unique_active_staff_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_manager',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch_number',
            field=models.CharField(default=branches.models.branch_number_generator, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_register_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('branch', 'register_number'), name='unique_register_number_per_branch'),
        ),
    ]
