# Generated by Django 6.1.1 on 2026-09-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0019_remove_staffassignment_unique_active_staff_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='branches.branches'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='branches.branches'),
        ),
    ]
