# Generated by Django 6.1.1 on 2026-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0021_alter_branches_branch_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registershift',
            name='note',
            field=models.TextField(blank=True, default='', help_text='What the person on the till wants the manager to know: a float taken for change, a jam, a customer coming back. Written during the shift and frozen when it closes.'),
        ),
    ]
