# Generated by Django 6.1.1 on 2026-10-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0022_registershift_note'),
        ('identity', '0005_staffpasswordreset_purpose'),
        ('organisations', '0025_businessorganization_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('float_in', 'Change brought in'), ('safe_drop', 'Dropped to the safe or banked'), ('pay_out', 'Paid out of the drawer')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='identity.platformaccount')),
                ('recorded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='organisations.organizationstaff')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='branches.registershift')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['shift', 'created_at'], name='branches_ca_shift_i_97ddae_idx')],
            },
        ),
    ]
