# Generated by Django 6.1.1 on 2026-10-01 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0022_registershift_note'),
        ('organisations', '0025_businessorganization_sector'),
        ('sales', '0003_saleitem_price_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (test)'), ('production', 'Production (real money)')], default='sandbox', help_text="Sandbox until the shop has tested it. Production moves real money out of real customers' accounts.", max_length=12)),
                ('short_code', models.CharField(help_text='The paybill or till number a customer would normally pay.', max_length=12)),
                ('transaction_type', models.CharField(choices=[('CustomerPayBillOnline', 'Paybill'), ('CustomerBuyGoodsOnline', 'Buy goods (till)')], default='CustomerPayBillOnline', max_length=24)),
                ('account_reference', models.CharField(blank=True, help_text="What appears on the customer's statement for a paybill. Ignored for buy-goods, which has no account.", max_length=24)),
                ('consumer_key_sealed', models.TextField(blank=True)),
                ('consumer_secret_sealed', models.TextField(blank=True)),
                ('passkey_sealed', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Off until the shop turns it on. A half-entered configuration that silently starts charging customers is the thing this prevents.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_till', to='organisations.businessorganization')),
            ],
            options={
                'verbose_name': 'M-Pesa till',
                'verbose_name_plural': 'M-Pesa tills',
            },
        ),
        migrations.CreateModel(
            name='StkPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('requested', 'Waiting for the customer'), ('paid', 'Paid'), ('failed', 'Not paid'), ('expired', 'Timed out')], default='requested', max_length=12)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32)),
                ('result_code', models.CharField(blank=True, max_length=8)),
                ('result_description', models.CharField(blank=True, max_length=255)),
                ('callback_token_digest', models.CharField(max_length=64, unique=True)),
                ('callback_seen_at', models.DateTimeField(blank=True, help_text='When a callback arrived. Recorded for diagnosis only — the status is decided by asking Safaricom, never by the callback.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stk_pushes', to='branches.branches')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stk_pushes', to='organisations.businessorganization')),
                ('requested_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_pushes', to='organisations.organizationstaff')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stk_push', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='payments_st_organiz_5f4311_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mpesa_receipt', ''), _negated=True), fields=('organization', 'mpesa_receipt'), name='unique_mpesa_receipt_per_organization')],
            },
        ),
    ]
