# Generated by Django 6.1.1 on 2026-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatill',
            name='store_number',
            field=models.CharField(blank=True, help_text='Buy-goods only: the store or head office number the passkey was issued against. Blank uses the till number for both.', max_length=12),
        ),
    ]
