# Generated by Django 6.1.1 on 2026-10-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0023_cashmovement'),
        ('organisations', '0025_businessorganization_sector'),
        ('payments', '0002_mpesatill_store_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatill',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave empty for the business default. Set it only where this branch is a separate Safaricom merchant with its own number.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_tills', to='branches.branches'),
        ),
        migrations.AddField(
            model_name='stkpush',
            name='till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pushes', to='payments.mpesatill'),
        ),
        migrations.AlterField(
            model_name='mpesatill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_tills', to='organisations.businessorganization'),
        ),
        migrations.AddConstraint(
            model_name='mpesatill',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('organization',), name='one_default_mpesa_till_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='mpesatill',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch',), name='one_mpesa_till_override_per_branch'),
        ),
    ]
