"""
Django settings for Business_Platform project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!^r3p(hw8mpbrzp6kno9bil2%d_6gua-4p*3m#pbx9*9d36zv)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'organisations',
    'rest_framework',
    'branches',
    'catalog',
    'inventory',
    'identity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Business_Platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {  
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Business_Platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-ke'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# IDENTITY AND ACCESS
# ═══════════════════════════════════════════════════════════════════════════

import os  # noqa: E402 - grouped with the settings it reads

# ── EVERY ENDPOINT IS CLOSED UNLESS IT SAYS OTHERWISE ──────────────────────
#
# There was no REST_FRAMEWORK block before this, so DRF's defaults applied:
# AllowAny, on every viewset, all of which were `Model.objects.all()`. Any
# caller could read and write every tenant's data.
#
# Defaulting to IsAuthenticated inverts that: a new viewset is shut until
# somebody opens it on purpose. Opening one is then a visible line in a diff,
# which is the point — the failure that matters here is the endpoint nobody
# remembered to protect.
#
# ⚠ Authentication is NOT closed by being listed here. A view still has to be
#   scoped: see identity/permissions.py `scoped()`. Knowing who is calling and
#   knowing what they may see are two different questions.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "identity.authentication.SubscriberSessionAuthentication",
        "identity.authentication.StaffTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Argon2 first, matching gen-portal. This database holds credentials belonging
# to OTHER COMPANIES' employees, which is a stronger reason to use the better
# hasher than the portal had. PBKDF2 stays so any hash written before this
# still verifies and is upgraded on its owner's next sign-in.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# ── THE GENMARS HANDOFF ────────────────────────────────────────────────────
#
# THE CLIENT SECRET IS A CREDENTIAL AND DOES NOT BELONG IN THIS FILE. It is
# read from the environment, it is shown exactly once when issued in ops
# (Settings -> Engineering -> Sibling sign-in), and it can only be replaced,
# never recovered.
#
# GENMARS_SIGN_ON_REDIRECT_URI must match what is registered there EXACTLY.
# The portal compares the whole string rather than a prefix, on purpose:
# prefix matching is how `https://business-os.genmars.co.ke.attacker.com/…`
# gets accepted. It must also be live https — the portal refuses localhost,
# IP literals and reserved TLDs, because a redirect address is where somebody
# holding a code that becomes their identity gets sent.
GENMARS_PORTAL_ORIGIN = os.environ.get(
    "GENMARS_PORTAL_ORIGIN", "https://app.genmars.co.ke"
)
GENMARS_API_ORIGIN = os.environ.get(
    "GENMARS_API_ORIGIN", "https://api.genmars.co.ke"
)
GENMARS_SIGN_ON_CLIENT_ID = os.environ.get("GENMARS_SIGN_ON_CLIENT_ID", "")
GENMARS_SIGN_ON_CLIENT_SECRET = os.environ.get("GENMARS_SIGN_ON_CLIENT_SECRET", "")
GENMARS_SIGN_ON_REDIRECT_URI = os.environ.get("GENMARS_SIGN_ON_REDIRECT_URI", "")
