"""
Django settings for Business_Platform project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ── SECRET_KEY ──────────────────────────────────────────────────────────────
#
# ⚠ THE KEY THAT USED TO BE ON THIS LINE IS IN THIS REPOSITORY'S HISTORY, AND
#   THIS REPOSITORY IS PUBLIC. It was the one `startproject` generates, it has
#   never run in production, and it must never be allowed to: anybody can read
#   it. Deleting it from this file does not unpublish it.
#
# Django signs session cookies and password-reset tokens with this. A known key
# means anybody can mint a session for anybody.
#
# The insecure default is kept ONLY so a fresh checkout runs without ceremony,
# and the guard below refuses to boot on it with DEBUG off.
DEV_ONLY_SECRET_KEY = "django-insecure-do-not-use-this-anywhere-real"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", DEV_ONLY_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Off unless something says otherwise. A missing environment variable must
# never be the thing that turns debug mode on in front of customers — DEBUG
# renders a stack trace, the settings and the SQL to whoever triggered the
# error.
DEBUG = os.environ.get("DEBUG", "False").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# ── THE WEB CONTAINER CALLS US BY OUR SERVICE NAME ──────────────────────────
#
# The Next.js frontend renders on the server and fetches this API over the
# compose network at http://api:8020, so Django sees `Host: api:8020`. Without
# this entry that is a DisallowedHost and EVERY server-rendered page is a 400 —
# which surfaces as a 500 in the browser and a log line about a host the
# frontend never mentions.
#
# It cannot be worked around from the frontend. Node's fetch treats `Host` as a
# forbidden header and strips it, computing the value from the URL; setting it
# explicitly is silently ignored. That was tried first.
#
# ⚠ WHY THIS DOES NOT WEAKEN ALLOWED_HOSTS.
#   The risk the setting exists to stop is Host-header poisoning from outside.
#   `api` is a name that only resolves on the internal compose network, and the
#   public edge is Caddy, whose site block matches on business.genmars.co.ke —
#   a request bearing any other Host does not reach Django at all. Adding a
#   name that cannot arrive from the internet costs nothing.
#
#   It is added HERE rather than to the ALLOWED_HOSTS environment variable so
#   the deployment's variable stays exactly the public name, and nobody has to
#   remember an internal detail when setting it.
ALLOWED_HOSTS += ["api"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'organisations',
    'rest_framework',
    'branches',
    'catalog',
    'inventory',
    'identity',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Business_Platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {  
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Business_Platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# ── DATABASE ────────────────────────────────────────────────────────────────
#
# Postgres in production, SQLite for a local checkout. Parsed by hand rather
# than with dj-database-url: one URL, one format, and Charter 03 §I admits a
# dependency only when what is here cannot do the job.
#
# SQLite is a development convenience and nothing more. It has no real
# concurrency, and a POS is a system where two tills write at the same moment
# by definition.
if os.environ.get("DATABASE_URL"):
    from urllib.parse import unquote, urlparse

    _url = urlparse(os.environ["DATABASE_URL"])
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _url.path.lstrip("/"),
            "USER": unquote(_url.username or ""),
            "PASSWORD": unquote(_url.password or ""),
            "HOST": _url.hostname or "",
            "PORT": str(_url.port or ""),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-ke'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# ── STATIC_ROOT ─────────────────────────────────────────────────────────────
#
# Where `collectstatic` writes. Unset by `startproject`, and without it
# collectstatic raises ImproperlyConfigured — which is how the first build of
# the production image failed.
#
# The only static files here are the Django admin's and DRF's browsable API.
# There is no frontend in this repository yet; when there is, it will serve its
# own assets and this stays what it is.
#
# Collected at image build time, not at boot: an entrypoint doing it would have
# every restart racing to write the same files, and the container runs with a
# read-only root filesystem so it could not write them anyway.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# ── EMAIL ───────────────────────────────────────────────────────────────────
#
# Django 6.1 replaced EMAIL_BACKEND with MAILERS, and defining both refuses to
# boot — worth knowing, because every example on the internet still shows the
# old name.
#
# ── THE KEY IS THE SWITCH ───────────────────────────────────────────────────
#
# Setting RESEND_API_KEY turns mail on. There is deliberately no second
# variable to remember: a key present with the backend still pointing at the
# console is a configuration that looks complete and drops every message, and
# it is the exact shape of mistake the warning below was written about.
#
# EMAIL_BACKEND still overrides, for the locmem backend in tests and for
# anybody who wants console output while a key happens to be set.
#
# `check --deploy` reports mail.E001 for the console backend. That report is
# TRUE and deliberately NOT silenced: with no key set nothing can send, the
# first feature that needs mail is resetting a cashier's password, and a reset
# that silently discards its own email is the worst possible way to discover
# this was never configured.
#
# Django 6.1 replaced EMAIL_BACKEND with MAILERS, and defining both refuses to
# boot — worth knowing, because every example on the internet still shows the
# old name.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")

# Resend refuses a From address on a domain that has not been verified with
# them, and answers with a readable reason rather than silently dropping it —
# see mail_backends.py on why that is the point of using the API.
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "info@genmars.co.ke")

# Ten seconds. A person is waiting on a password reset; a mail provider that
# has not answered by then is not about to.
#
# ⚠ NOT `EMAIL_TIMEOUT`. Django 6.1 refuses to boot when a deprecated email
#   setting is defined alongside MAILERS, and EMAIL_TIMEOUT is one of them —
#   the same trap this block already warns about for EMAIL_BACKEND, which is
#   easy to walk into precisely because gen-portal still uses the old name.
RESEND_TIMEOUT = int(os.environ.get("RESEND_TIMEOUT", "10"))

_DEFAULT_MAILER = (
    "Business_Platform.mail_backends.ResendBackend"
    if RESEND_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)

MAILERS = {
    "default": {
        "BACKEND": os.environ.get("EMAIL_BACKEND", _DEFAULT_MAILER),
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# IDENTITY AND ACCESS
# ═══════════════════════════════════════════════════════════════════════════


# ── EVERY ENDPOINT IS CLOSED UNLESS IT SAYS OTHERWISE ──────────────────────
#
# There was no REST_FRAMEWORK block before this, so DRF's defaults applied:
# AllowAny, on every viewset, all of which were `Model.objects.all()`. Any
# caller could read and write every tenant's data.
#
# Defaulting to IsAuthenticated inverts that: a new viewset is shut until
# somebody opens it on purpose. Opening one is then a visible line in a diff,
# which is the point — the failure that matters here is the endpoint nobody
# remembered to protect.
#
# ⚠ Authentication is NOT closed by being listed here. A view still has to be
#   scoped: see identity/permissions.py `scoped()`. Knowing who is calling and
#   knowing what they may see are two different questions.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "identity.authentication.SubscriberSessionAuthentication",
        "identity.authentication.StaffTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Argon2 first, matching gen-portal. This database holds credentials belonging
# to OTHER COMPANIES' employees, which is a stronger reason to use the better
# hasher than the portal had. PBKDF2 stays so any hash written before this
# still verifies and is upgraded on its owner's next sign-in.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# ── THE GENMARS HANDOFF ────────────────────────────────────────────────────
#
# THE CLIENT SECRET IS A CREDENTIAL AND DOES NOT BELONG IN THIS FILE. It is
# read from the environment, it is shown exactly once when issued in ops
# (Settings -> Engineering -> Sibling sign-in), and it can only be replaced,
# never recovered.
#
# GENMARS_SIGN_ON_REDIRECT_URI must match what is registered there EXACTLY.
# The portal compares the whole string rather than a prefix, on purpose:
# prefix matching is how `https://business-os.genmars.co.ke.attacker.com/…`
# gets accepted. It must also be live https — the portal refuses localhost,
# IP literals and reserved TLDs, because a redirect address is where somebody
# holding a code that becomes their identity gets sent.
GENMARS_PORTAL_ORIGIN = os.environ.get(
    "GENMARS_PORTAL_ORIGIN", "https://app.genmars.co.ke"
)
GENMARS_API_ORIGIN = os.environ.get(
    "GENMARS_API_ORIGIN", "https://api.genmars.co.ke"
)
GENMARS_SIGN_ON_CLIENT_ID = os.environ.get("GENMARS_SIGN_ON_CLIENT_ID", "")
GENMARS_SIGN_ON_CLIENT_SECRET = os.environ.get("GENMARS_SIGN_ON_CLIENT_SECRET", "")
GENMARS_SIGN_ON_REDIRECT_URI = os.environ.get("GENMARS_SIGN_ON_REDIRECT_URI", "")


# ═══════════════════════════════════════════════════════════════════════════
# REFUSING TO BOOT ON A CONFIGURATION THAT WOULD BE UNSAFE
# ═══════════════════════════════════════════════════════════════════════════
#
# The same approach gen-portal takes: every failure guarded here is one that is
# INVISIBLE at runtime. A platform running on the public secret key serves
# every page correctly; a platform with DEBUG on looks fine until the first
# exception shows a stranger the settings. Refusing to start is loud, happens
# at deploy time, and happens to us rather than to a customer.

# ── WHY THE TEST RUNNER IS EXCLUDED, AND WHAT THAT COSTS ────────────────────
#
# Django's test runner forces DEBUG = False, so without this every one of the
# guards below would fire on `manage.py test` and the suite could not run at
# all.
#
# The cost is real and worth naming: the tests therefore do NOT exercise the
# production configuration. Nothing here proves a deployed process boots. That
# is what the deploy-time check is for, and it belongs in CI:
#
#   DEBUG=False DJANGO_SECRET_KEY=… ALLOWED_HOSTS=… CSRF_TRUSTED_ORIGINS=… \
#   DATABASE_URL=… python manage.py check --deploy
#
# gen-portal runs exactly that as its own step, because guards that are never
# executed against a real configuration are guards nobody has tested.
RUNNING_TESTS = "test" in sys.argv

if not DEBUG and not RUNNING_TESTS:
    from django.core.exceptions import ImproperlyConfigured

    if SECRET_KEY == DEV_ONLY_SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is not set, so this would run on the key that "
            "is committed to a public repository. Django signs session cookies "
            "with it — a known key means anybody can mint a session for "
            "anybody. Generate one and set it."
        )

    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS is empty. Set it to the public hostname, e.g. "
            "ALLOWED_HOSTS=business.genmars.co.ke"
        )

    if "sqlite3" in DATABASES["default"]["ENGINE"]:
        raise ImproperlyConfigured(
            "DATABASE_URL is not set, so this would run on SQLite. Two tills "
            "writing at the same moment is the normal case for a POS, and "
            "SQLite has no answer for it. Point DATABASE_URL at Postgres."
        )

    # ── BEHIND CADDY ────────────────────────────────────────────────────────
    #
    # Caddy terminates TLS and proxies over plain HTTP on the loopback, so
    # Django cannot see that the browser used https unless it is told. Without
    # this, `request.is_secure()` is False, secure cookies are never set, and
    # any redirect Django builds comes back as http.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Caddy already redirects http to https; doing it here as well loops.
    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    X_FRAME_OPTIONS = "DENY"

    # ⚠ NO SESSION_COOKIE_DOMAIN, EVER.
    #
    # Leaving it unset scopes the cookie to business.genmars.co.ke alone. Set
    # it to ".genmars.co.ke" and this platform's session starts riding along to
    # app., api. and ops. — which is exactly the separation that keeps a
    # subscriber's session here from being replayable against the portal.
    # gen-portal carries the same warning in two places.

    # ── CHECKS SILENCED, AND WHY ────────────────────────────────────────────
    #
    # W004 (SECURE_HSTS_SECONDS unset) and W008 (SECURE_SSL_REDIRECT not True)
    # are both about things Caddy does at the TLS edge. Setting either here
    # would be the wrong layer: HSTS is meaningless on the plain-HTTP hop
    # behind the proxy, and redirecting twice loops. Same call, same reasons,
    # as gen-portal.
    #
    # ⚠ NOTHING ELSE GOES IN THIS LIST without a line saying why. A silenced
    # check is a check nobody will ever see again.
    SILENCED_SYSTEM_CHECKS = ["security.W004", "security.W008"]

    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured(
            "CSRF_TRUSTED_ORIGINS is empty. Without it every authenticated "
            "POST is rejected while signing in still appears to work, which is "
            "the most misleading way this can fail."
        )
